name: CI with cache

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 1) Cache step: primes/restores ~/.npm with the fixed key
      - name: Cache npm cache dir
        id: deps-cache
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: cache-7799caf

      # 2) REQUIRED by the prompt: echo whether cache hit or miss
      - name: prime-cache-7799caf
        run: echo "cache-hit: ${{ steps.deps-cache.outputs.cache-hit }}"

      # 3) Install deps (this populates ~/.npm; on a miss, cache is saved after job)
      - name: Install deps
        run: npm ci

      - name: Build (example)
        run: npm run build --if-present
