name: CI with cache

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Create a directory we will cache (no language runtime needed)
      - name: Prepare cache dir
        run: |
          mkdir -p .ci-cache/demo
          echo "seed-$(date +%s)" > .ci-cache/demo/seed.txt

      # The required cache step
      - name: Cache demo dir
        id: deps-cache
        uses: actions/cache@v4
        with:
          path: .ci-cache
          key: cache-7799caf

      # The required echo step
      - name: prime-cache-7799caf
        run: echo "cache-hit: ${{ steps.deps-cache.outputs['cache-hit'] }}"

      # Prove job keeps running and succeeds
      - name: Finish
        run: |
          echo "Cached files:"
          ls -la .ci-cache || true
