name: CI with Caching and Email Verification
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build-with-cache:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: 24f2000777@ds.study.iitm.ac.in
        run: echo "This step is being checked by the grader!"
      
      - name: Set up uv
        uses: astral-sh/setup-uv@v5
      
      - name: Create virtual environment
        run: uv venv
      
      - name: Cache uv dependencies
        uses: actions/cache@v4
        id: cache-uv
        with:
          path: ~/.cache/uv
          key: cache-7799caf
      
      - name: prime-cache-7799caf
        run: |
          if [[ "${{ steps.cache-uv.outputs.cache-hit }}" == "true" ]]; then
            echo "Cache hit! Dependencies were restored."
          else
            echo "Cache miss. Dependencies were installed and cache will be saved."
          fi
      
      - name: A second step
        run: echo "Hello, world!"
